---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: instrumentisto/glide
    tag: 0.13

inputs:
  - name: golang-starter-src

run:
  path: sh
  args:
    - -exc
    - |
      ./ci/scripts/ensure_deps.sh
      ./ci/scripts/unit_tests.sh
  dir: golang-starter-src
